"""
Data Privacy in Elite Performance: Protecting Athlete Biometrics
Week 8: Full System Integration Test Suite — Master Runner

Asserts 100% test passage across all 7 prior implementation weeks, then
runs Week 8 specific smoke tests validating the benchmark and ledger outputs.

Usage:
    python -m pytest test_full_system_week8.py -v
    python test_full_system_week8.py          # run directly

Architecture
------------
The prior-week suite discovery uses unittest.TestLoader which imports each
test module and runs every TestCase it finds.  The results are collected and
asserted via ``result.wasSuccessful()``.  A single failure in any prior week
will fail this master suite — giving the instructor a single command that
proves complete system health.

Week 8 Smoke Tests
------------------
1. EVALUATION_RESULTS.json exists and contains all 7 required metric keys.
2. validate_chain() returns True on the production ledger_file.json.
3. AES-256-GCM encryption overhead < 2 ms (per instructor threshold).
4. API response times < 20 ms for all endpoints (realistic upper bound).
5. 100% successful request rate on valid requests.
6. 100% failed request rate on blocked (RBAC/GDPR) requests.
"""

from __future__ import annotations

import json
import os
import unittest

# ---------------------------------------------------------------------------
# Prior-week test modules (collected and run as a sub-suite)
# ---------------------------------------------------------------------------
PRIOR_WEEK_MODULES = [
    "test_week1",
    "test_pipeline_week3",
    "test_pipeline_week5",
    "test_pipeline_week6",
    "test_pipeline_week7",
]

EVALUATION_RESULTS_PATH = "EVALUATION_RESULTS.json"
LEDGER_PATH = "ledger_file.json"


def _load_evaluation_results() -> dict:
    """Load EVALUATION_RESULTS.json, skipping if not yet generated."""
    if not os.path.exists(EVALUATION_RESULTS_PATH):
        return {}
    with open(EVALUATION_RESULTS_PATH, encoding="utf-8") as fh:
        return json.load(fh)


# ===========================================================================
# Prior-week regression suite (run as a single test)
# ===========================================================================

class TestPriorWeeksRegression(unittest.TestCase):
    """
    Runs all 114 prior-week tests (Weeks 1–7) inside a single assertion.
    A failure in any prior week will fail this class — ensuring no regression
    is introduced by Week 8 changes.
    """

    def test_all_prior_weeks_pass(self) -> None:
        """
        Load and execute all prior-week test modules.
        Fails this test if ANY prior test produces a failure or error.
        """
        loader = unittest.TestLoader()
        suite = unittest.TestSuite()

        for module_name in PRIOR_WEEK_MODULES:
            try:
                module_suite = loader.loadTestsFromName(module_name)
                suite.addTests(module_suite)
            except ModuleNotFoundError as exc:
                self.fail(f"Could not import test module '{module_name}': {exc}")

        # Run in a buffer so prior-week stdout does not pollute pytest output.
        runner = unittest.TextTestRunner(stream=open(os.devnull, "w"), verbosity=0)
        result = runner.run(suite)

        total = result.testsRun
        failures = len(result.failures)
        errors = len(result.errors)

        if not result.wasSuccessful():
            msgs = [f"Prior-week regression FAILED: {total} tests run, "
                    f"{failures} failures, {errors} errors."]
            for test, tb in result.failures + result.errors:
                msgs.append(f"\n  FAIL: {test}\n  {tb[:500]}")
            self.fail("\n".join(msgs))

        # Confirm expected test count hasn't shrunk unexpectedly.
        self.assertGreaterEqual(
            total, 114,
            f"Expected ≥ 114 prior-week tests but only {total} ran — possible import error.",
        )


# ===========================================================================
# Week 8 Smoke Tests
# ===========================================================================

class TestEvaluationResultsIntegrity(unittest.TestCase):
    """Validate the contents and metric values of EVALUATION_RESULTS.json."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.results = _load_evaluation_results()

    def test_evaluation_results_file_exists(self) -> None:
        """EVALUATION_RESULTS.json must exist (generated by benchmark_evaluation.py)."""
        self.assertTrue(
            os.path.exists(EVALUATION_RESULTS_PATH),
            f"'{EVALUATION_RESULTS_PATH}' not found — run `python benchmark_evaluation.py` first.",
        )

    def test_all_metric_keys_present(self) -> None:
        """All 7 instructor-specified metric keys must be present in the JSON."""
        required_keys = {
            "benchmark_iterations",
            "successful_request_rate_pct",
            "failed_request_rate_pct",
            "avg_response_times_ms",
            "encryption_overhead_ms",
            "decryption_overhead_ms",
            "throughput_req_per_sec",
            "storage_overhead",
        }
        if not self.results:
            self.skipTest("EVALUATION_RESULTS.json is empty or missing.")
        missing = required_keys - set(self.results.keys())
        self.assertFalse(
            missing,
            f"Missing metric keys in EVALUATION_RESULTS.json: {sorted(missing)}",
        )

    def test_response_times_all_endpoints_populated(self) -> None:
        """avg_response_times_ms must contain entries for all 4 endpoints."""
        if not self.results:
            self.skipTest("EVALUATION_RESULTS.json is empty or missing.")
        rt = self.results.get("avg_response_times_ms", {})
        for ep in ("ingest", "consent", "authorize_decrypt", "transfer"):
            self.assertIn(ep, rt, f"Response time missing for endpoint '{ep}'.")

    def test_storage_overhead_all_fields_present(self) -> None:
        """storage_overhead must contain all 5 sub-fields."""
        if not self.results:
            self.skipTest("EVALUATION_RESULTS.json is empty or missing.")
        st = self.results.get("storage_overhead", {})
        for key in ("raw_biometric_bytes", "ciphertext_bytes", "audit_row_bytes",
                    "ledger_block_bytes", "ciphertext_overhead_pct"):
            self.assertIn(key, st, f"Storage overhead field '{key}' missing.")

    def test_successful_request_rate_is_100_percent(self) -> None:
        """Valid requests must achieve a 100% success rate."""
        if not self.results:
            self.skipTest("EVALUATION_RESULTS.json is empty or missing.")
        rate = self.results.get("successful_request_rate_pct", 0)
        self.assertEqual(rate, 100.0, f"Expected 100.0% but got {rate}%.")

    def test_failed_request_rate_is_100_percent(self) -> None:
        """Blocked (RBAC/GDPR) requests must achieve a 100% failure (4xx) rate."""
        if not self.results:
            self.skipTest("EVALUATION_RESULTS.json is empty or missing.")
        rate = self.results.get("failed_request_rate_pct", 0)
        self.assertEqual(rate, 100.0, f"Expected 100.0% but got {rate}%.")

    def test_encryption_overhead_under_2ms(self) -> None:
        """
        AES-256-GCM encryption overhead must be < 2 ms — validating the
        instructor's claim that cryptographic overhead is operationally negligible.
        """
        if not self.results:
            self.skipTest("EVALUATION_RESULTS.json is empty or missing.")
        overhead = self.results.get("encryption_overhead_ms", 999)
        self.assertLess(
            overhead, 2.0,
            f"Encryption overhead {overhead:.3f} ms exceeds 2 ms threshold.",
        )

    def test_all_api_response_times_under_20ms(self) -> None:
        """All endpoint response times must be < 20 ms (realistic upper bound)."""
        if not self.results:
            self.skipTest("EVALUATION_RESULTS.json is empty or missing.")
        rt = self.results.get("avg_response_times_ms", {})
        for ep, ms in rt.items():
            self.assertLess(
                ms, 20.0,
                f"Endpoint '{ep}' avg response time {ms:.2f} ms exceeds 20 ms.",
            )

    def test_benchmark_ran_100_iterations(self) -> None:
        """Benchmark must have completed exactly 100 iterations."""
        if not self.results:
            self.skipTest("EVALUATION_RESULTS.json is empty or missing.")
        self.assertEqual(self.results.get("benchmark_iterations"), 100)


class TestLedgerIntegrity(unittest.TestCase):
    """Validate the production ledger file (ledger_file.json)."""

    def test_ledger_file_exists(self) -> None:
        """ledger_file.json must exist (created by the server on startup)."""
        self.assertTrue(
            os.path.exists(LEDGER_PATH),
            f"'{LEDGER_PATH}' not found — start the server at least once.",
        )

    def test_production_ledger_chain_is_valid(self) -> None:
        """validate_chain() must return True on the production ledger."""
        if not os.path.exists(LEDGER_PATH):
            self.skipTest(f"'{LEDGER_PATH}' not found.")
        from ledger.local_hashed_ledger import LocalHashedLedger
        ledger = LocalHashedLedger(ledger_file_json=LEDGER_PATH)
        self.assertTrue(
            ledger.validate_chain(),
            "Production ledger_file.json failed chain validation — possible tampering!",
        )

    def test_ledger_has_genesis_block(self) -> None:
        """ledger_file.json must contain at least the genesis block (index 0)."""
        if not os.path.exists(LEDGER_PATH):
            self.skipTest(f"'{LEDGER_PATH}' not found.")
        from ledger.local_hashed_ledger import LocalHashedLedger
        ledger = LocalHashedLedger(ledger_file_json=LEDGER_PATH)
        chain = ledger.get_chain()
        self.assertGreaterEqual(len(chain), 1, "Ledger must have at least a genesis block.")
        self.assertEqual(chain[0]["index"], 0)
        self.assertEqual(chain[0]["player_id"], "GENESIS")


# ===========================================================================
# Entry point — also usable directly without pytest
# ===========================================================================

if __name__ == "__main__":
    unittest.main(verbosity=2)
